:domain = http://localhost:8181
:url = :domain/api/v1
:headers = <<
Content-Type: application/json
#

# actuator
GET :domain/actuator/mappings

### Authors

# GET /authors
GET :url/authors
:headers

# GET /authors/:id
:id = 4
GET :url/authors/:id
:headers

# POST /authors
POST :url/authors
:headers
{
"firstName": "first",
"lastName": "last",
"email": "dsdssssimeidaadaldd@gamil.com",
"dateOfBirth": "1956-02-24"
}

# PATCH /authors/id
:id = 4
PATCH :url/authors/:id
:headers
{
"firstName": "firsttt"
}

# DELETE /authors/id
:id = 5
DELETE :url/authors/:id
:headers

### Publishers

# GET /publishers
GET :url/publishers
:heade
rs

# GET /publishers/:id
:id = 1
GET :url/publishers/:id
:headers

# POST /publishers
POST :url/publishers
:headers
{
"name": "name 4",
"address": "addressss"
}

# PATCH /publishers/id
:id = 1
PATCH :url/publishers/:id
:headers
{
"name": "new name"
}

# DELETE /publishers/id
:id = 3
DELETE :url/publishers/:id
:headers

### Books

# GET /books
GET :url/books
:headers

# GET /books/:id
:id = 1
GET :url/books/:id
:headers

# POST /books
POST :url/books
:headers
{
"title": "book 193933",
"description": "dkdlak kldsalk jfdlkjdlk jkldjld k",
"isbn": "illsdddddidndddd",
"authorId": 1,
"publisherId": 1
}

# PATCH /books/id
:id = 1
PATCH :url/books/:id
:headers
{
"title": "update titleee 2"
}

# DELETE /books/id
:id = 3
DELETE :url/books/:id
:headers