server:
  port: 8181

logging:
  level:
    root: INFO
    org:
      springframework: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore_development?createDatabaseIfNotExist=true
    username: dev
    password: dev
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    show-sql: true
  properties:
    hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    schemas: public
    url: ${spring.datasource.url}
    locations: filesystem:migration

mapstruct:
  verbose: true
