server:
  port: 8181

logging:
  level:
    root: INFO
    org:
      springframework: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  profiles:
    default: dev
  jackson:
    serialization:
      write-dates-as-timestamps: false
  mvc:
    format:
      date: yyyy-MM-dd
      time: iso
      date-time: iso
  datasource:
    url:
    username:
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    show-sql: true
  flyway:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    schemas: public
    locations: classpath:db/migration

mapstruct:
  verbose: true
